FROM python:3.7

RUN apt-get update && \
	apt-get install -y git

RUN mkdir /app
WORKDIR /app

RUN wget https://github.com/RomainUSA/CBCT_seg/archive/refs/tags/v2.3.zip
RUN unzip v2.3.zip
RUN mv CBCT_seg-2.3/src src
RUN rm -rf v2.3.zip \
	rm -rf CBCT_seg-2.3

RUN pip3 install -r /app/src/requirements.txt

RUN mkdir /app/model
WORKDIR /app/model
RUN wget https://github.com/RomainUSA/CBCT_seg/releases/download/v2.3/MandSeg_256_FullDA_1_40.hdf5

